"""Golden test: the traceEvents array for the valid fixture is frozen.

The golden file was generated by the converter and verified event-by-event
against hand-computed timestamps, durations, and counter values
(ctx_* = per-call occupancy, spend_* = cumulative session sums; see
tests/fixtures/valid_session.jsonl). Regenerate only when the fixture
or the mapping changes intentionally.
"""

import json
from pathlib import Path

from agent2perfetto.parser import parse_file
from agent2perfetto.trace import build_trace

FIXTURES = Path(__file__).parent / "fixtures"


def test_trace_events_match_golden():
    golden = json.loads((FIXTURES / "golden_trace_events.json").read_text(encoding="utf-8"))
    trace = build_trace(parse_file(FIXTURES / "valid_session.jsonl"))
    assert trace["traceEvents"] == golden


def test_rebuild_is_deterministic():
    first = build_trace(parse_file(FIXTURES / "valid_session.jsonl"), generated_at="2026-09-05T00:00:00Z")
    second = build_trace(parse_file(FIXTURES / "valid_session.jsonl"), generated_at="2026-09-05T00:00:00Z")
    assert first == second
